version: '3.8'

services:
  frontend:
    build: ./Frontend
    ports:
      - "8080:80"
    networks:
      - kfc-network

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - frontend
    networks:
      - kfc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      retries: 3

networks:
  kfc-network:
